CREATE TABLE "LIFE_EXPECTANCY_TABLE" (
	"COUNTRY"	TEXT,
	"YEAR"	INTEGER,
	"STATUS"	TEXT,
	"LIFE_EXPECTANCY"	REAL,
	"ADULT_MORTALITY"	INTEGER,
	"INFANT_DEATHS"	INTEGER,
	"ALCOHOL"	REAL,
	"PERCENT_EXPENDITURE"	REAL,
	"HEPATITUS_B"	INTEGER,
	"MEASLES"	INTEGER,
	"BMI"	REAL,
	"UNDER_FIVE_DEATHS"	INTEGER,
	"POLIO"	INTEGER,
	"TOTAL_EXPENDITURE"	REAL,
	"DIPTHERIA"	INTEGER,
	"HIV_AIDS"	REAL,
	"GDP"	REAL,
	"POPULATION"	INTEGER,
	"THINNESS_1_TO_19_YRS"	REAL,
	"THINNESS_5_TO_9_YRS"	REAL,
	"INCOME_COMP_RESOURCES"	REAL,
	"SCHOOLING"	REAL
);

/* Source data location
https://www.kaggle.com/kumarajarshi/life-expectancy-who?select=Life+Expectancy+Data.csv
*/
